# This is the compose file for live development
# All code is mounted from local file system and recompiled as needed
version: '3.3'

services:
  symfony:
    image: symfony
    volumes:
      # application code
      - ${PWD}:/var/www/html
      # - ${PWD}/php-logs:/home/root/php-logs
    ports:
      - 80:80
    restart: "no"