# This is the compose file for live development
# All code is mounted from local file system and recompiled as needed
version: '3.3'

services:
  php:
    container_name: symfony4.1-php7.1
    image: jjosep1989/symfony:4.1-alpine
    volumes:
      - ${PWD}:/app
    ports:
      - 8000:8000
    links:
      - database
    restart: "no"          
  database:
    container_name: symfony4.1-mariadb
    image: bianjp/mariadb-alpine
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/db_data:/var/lib/mysql    
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_USER : maria
      MYSQL_PASSWORD : maria
      MYSQL_DATABASE: test
    restart: "no"