# This is the compose file for live development
# All code is mounted from local file system and recompiled as needed
version: '3.3'

services:
  symfony:
    image: jjosep1989/symfony4-with-docker
    volumes:
      # application code
      - ${PWD}:/var/www/html
      - ${PWD}/php-logs:/php-logs
    ports:
      - 80:80
    restart: "no"